+incdir+$RVGPU_HARDWARE/rtl/core/iu
+incdir+$RVGPU_HARDWARE/rtl/core/ifu
+incdir+$RVGPU_HARDWARE/rtl/core/ifu/icache
+incdir+$RVGPU_HARDWARE/rtl/clk
+incdir+$RVGPU_HARDWARE/rtl/common
+incdir+$RVGPU_HARDWARE/rtl/common/sm
+incdir+$RVGPU_HARDWARE/rtl/common/gpc
+incdir+$RVGPU_HARDWARE/rtl/common/cache
+incdir+$RVGPU_HARDWARE/rtl/common/command
+incdir+$RVGPU_HARDWARE/rtl/common/config
+incdir+$RVGPU_HARDWARE/rtl/common/fifo
+incdir+$RVGPU_HARDWARE/rtl/common/mmu
+incdir+$RVGPU_HARDWARE/rtl/common/sram
+incdir+$RVGPU_HARDWARE/rtl/common/noc
+incdir+$RVGPU_HARDWARE/rtl/interface
+incdir+$RVGPU_HARDWARE/rtl/gpu_top
+incdir+$RVGPU_HARDWARE/rtl/internal_noc
+incdir+$RVGPU_HARDWARE/rtl/control_unit
+incdir+$RVGPU_HARDWARE/rtl/l2cache
+incdir+$RVGPU_HARDWARE/rtl/gpc
+incdir+$RVGPU_HARDWARE/rtl/gpc/cache
+incdir+$RVGPU_HARDWARE/rtl/sm
+incdir+$RVGPU_HARDWARE/rtl/cudacore