Import('env')

# 创建头文件安装目录
inc_dir = env.Dir('include')

# 安装头文件
env.Install(env['INSTALL_INCLUDE'], 'rvgpu_simulator.hpp')
env.Install(env['INSTALL_INCLUDE'], 'rvgpu_simtop.hpp')
env.Install(env['INSTALL_INCLUDE'], 'rvgpu_registers.hpp')

# 构建共享库
lib = env.SharedLibrary(
    target='librvgpu_simulator',
    source=['rvgpu_simulator.cpp'],
    LIBS=['stdc++'],
)

# 安装库文件
env.Install(env['INSTALL_LIB64'], lib)

# 返回库文件供其他模块使用
Return('lib') 