Import('env')

# 构建共享库
lib = env.SharedLibrary(
    target='librvgpu_csim',
    source=['rvgpu_csim.cpp'],
    LIBS=['stdc++'],
)

# 安装库文件
env.Install(env['INSTALL_LIB64'], lib)

# 返回库文件供其他模块使用
Return('lib') 