Import('env')

# 数组加法测试程序
# SCons会自动处理库依赖，我们只需要指定库名
exe = env.Program(
    target='rvgpu_test_array_add',
    source=['rvgpu_test_array_add.cpp'],
    CPPPATH=['../simtop', '../csim', '../rtlsim'],
    LIBPATH=['../simtop', '../csim', '../rtlsim'],  # 添加所有库搜索路径
    LIBS=['stdc++', 'rvgpu_simulator', 'rvgpu_csim', 'rvgpu_rtlsim'],
)

# 安装可执行文件
env.Install(env['INSTALL_BIN'], exe) 